# Generated by Django 4.1.7 on 2023-03-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_mode', models.TextField(default='academia')),
                ('input_question', models.TextField(default='Ask q/a here')),
                ('result', models.TextField(default='')),
                ('related_link_one', models.TextField(default='')),
                ('related_link_two', models.TextField(default='')),
                ('related_link_three', models.TextField(default='')),
                ('img_link', models.TextField(default='')),
            ],
        ),
    ]
